# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Salem/Desktop/Uvod2/Uvod2/Uvod2.srcs/sources_1/bd/Uvod2/ip/Uvod2_clk_wiz_0_0/Uvod2_clk_wiz_0_0.xci
# IP: The module: 'Uvod2_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Salem/Desktop/Uvod2/Uvod2/Uvod2.gen/sources_1/bd/Uvod2/ip/Uvod2_clk_wiz_0_0/Uvod2_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Uvod2_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Salem/Desktop/Uvod2/Uvod2/Uvod2.gen/sources_1/bd/Uvod2/ip/Uvod2_clk_wiz_0_0/Uvod2_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Uvod2_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Salem/Desktop/Uvod2/Uvod2/Uvod2.gen/sources_1/bd/Uvod2/ip/Uvod2_clk_wiz_0_0/Uvod2_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Uvod2_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Salem/Desktop/Uvod2/Uvod2/Uvod2.srcs/sources_1/bd/Uvod2/ip/Uvod2_clk_wiz_0_0/Uvod2_clk_wiz_0_0.xci
# IP: The module: 'Uvod2_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Salem/Desktop/Uvod2/Uvod2/Uvod2.gen/sources_1/bd/Uvod2/ip/Uvod2_clk_wiz_0_0/Uvod2_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Uvod2_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Salem/Desktop/Uvod2/Uvod2/Uvod2.gen/sources_1/bd/Uvod2/ip/Uvod2_clk_wiz_0_0/Uvod2_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Uvod2_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Salem/Desktop/Uvod2/Uvod2/Uvod2.gen/sources_1/bd/Uvod2/ip/Uvod2_clk_wiz_0_0/Uvod2_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Uvod2_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
