# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/Uvod2/Uvod2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Uvod2 || ORIG_REF_NAME==Uvod2} -quiet] -quiet

# IP: bd/Uvod2/ip/Uvod2_clk_wiz_0_0/Uvod2_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Uvod2_clk_wiz_0_0 || ORIG_REF_NAME==Uvod2_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Uvod2/ip/Uvod2_debounce_0_0/Uvod2_debounce_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Uvod2_debounce_0_0 || ORIG_REF_NAME==Uvod2_debounce_0_0} -quiet] -quiet

# IP: bd/Uvod2/ip/Uvod2_debounce_0_1/Uvod2_debounce_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Uvod2_debounce_0_1 || ORIG_REF_NAME==Uvod2_debounce_0_1} -quiet] -quiet

# IP: bd/Uvod2/ip/Uvod2_debounce_0_2/Uvod2_debounce_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Uvod2_debounce_0_2 || ORIG_REF_NAME==Uvod2_debounce_0_2} -quiet] -quiet

# IP: bd/Uvod2/ip/Uvod2_debounce_0_3/Uvod2_debounce_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Uvod2_debounce_0_3 || ORIG_REF_NAME==Uvod2_debounce_0_3} -quiet] -quiet

# IP: bd/Uvod2/ip/Uvod2_svga_0_0/Uvod2_svga_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Uvod2_svga_0_0 || ORIG_REF_NAME==Uvod2_svga_0_0} -quiet] -quiet

# IP: bd/Uvod2/ip/Uvod2_top_0_0/Uvod2_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Uvod2_top_0_0 || ORIG_REF_NAME==Uvod2_top_0_0} -quiet] -quiet

# XDC: c:/Users/vaje/Desktop/Salem/SalemPEV/2.5/PEV/Projekt/Projekt.gen/sources_1/bd/Uvod2/Uvod2_ooc.xdc
